# Generated by Django 3.0.7 on 2020-06-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cercaeletrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perimetro', models.FloatField(verbose_name='Perimetro')),
                ('elevacao', models.IntegerField(verbose_name='Elevação')),
                ('cantoneira', models.IntegerField(verbose_name='Cantos')),
                ('qtd_isolador', models.IntegerField(verbose_name='Qauntidade de isoladores')),
                ('tipo_cerca', models.CharField(choices=[('Industrial', 'Industrial'), ('Semi-industrial', 'Semi-industrial'), ('Convencional', 'Convencional')], default='Industrial', max_length=15, verbose_name='Tipo de cerca')),
            ],
        ),
    ]
