# Generated by Django 3.0.7 on 2020-06-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CercaOrcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perimetro', models.FloatField(verbose_name='Perimetro')),
                ('elevacao', models.IntegerField(verbose_name='Elevação')),
                ('cantoneira', models.IntegerField(verbose_name='Cantos')),
                ('qtd_isolador', models.IntegerField(verbose_name='Qauntidade de isoladores')),
                ('tipo_cerca', models.CharField(choices=[('Industrial', 'Industrial'), ('Semi-industrial', 'Semi-industrial'), ('Convencional', 'Convencional')], default='Industrial', max_length=15, verbose_name='Tipo de cerca')),
                ('imagem', models.ImageField(upload_to='cercas', verbose_name='Imagem')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Cerca Eletrica',
                'verbose_name_plural': 'Cercas Eletricas',
            },
        ),
        migrations.DeleteModel(
            name='Cercaeletrica',
        ),
    ]
