# Generated by Django 3.0.7 on 2020-06-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cftv', '0003_auto_20200627_1418'),
        ('cerca', '0002_auto_20200622_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentocerca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento_cerca', models.CharField(max_length=100, verbose_name='Equipamento')),
                ('potencia', models.FloatField(blank=True, null=True, verbose_name='Potência')),
                ('metros_linear', models.IntegerField(blank=True, null=True, verbose_name='Distancia doperimetro')),
                ('haste_tipo', models.CharField(blank=True, choices=[('Indsutrial 6', 'INDUSTRIAL 6 ISOLADORES'), ('SEMI INDUSTRIAL 4', 'SEMI INDUSTRIAL 4 ISOLADORES')], max_length=29, null=True, verbose_name='Tipo de haste')),
                ('tamanho', models.FloatField(blank=True, null=True, verbose_name='Tamanho')),
                ('bitola_arame', models.FloatField(blank=True, null=True, verbose_name='Bitola do fio de aço')),
                ('cabo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cabo', to='cftv.Cabo', verbose_name='Cabo')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabricante', to='cftv.Fabricante', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
