# Generated by Django 3.0.7 on 2020-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerca', '0003_equipamentocerca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cercaorcamento',
            options={'verbose_name': ' Orçamento Cerca Eletrica', 'verbose_name_plural': 'Orçamento Cercas Eletricas'},
        ),
        migrations.AlterField(
            model_name='cercaorcamento',
            name='qtd_isolador',
            field=models.IntegerField(verbose_name='Quantidade de isoladores'),
        ),
    ]
