# Generated by Django 3.0.7 on 2020-07-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('email', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('numero', models.CharField(max_length=5, verbose_name='Numero/Quadra/Lote')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('ponto_referencia', models.CharField(max_length=100, verbose_name='Ponto de referencia')),
            ],
            options={
                'verbose_name': 'CLiente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
