# Generated by Django 3.0.7 on 2020-06-23 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CftvOrcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], max_length=10, verbose_name='Ambiente')),
                ('imagem', models.ImageField(upload_to='local', verbose_name='Imagem do local')),
                ('local', models.CharField(max_length=80, verbose_name='Local')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição do local')),
            ],
            options={
                'verbose_name': 'Orçamento CFTV',
                'verbose_name_plural': 'Orçamentos CFTV',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=100, verbose_name='Equipamento')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('infra', models.IntegerField(verbose_name='Distania do Infra vermelho')),
                ('lente', models.FloatField(verbose_name='Tamanho da lente')),
                ('consumo_amper', models.FloatField(verbose_name='Consumo em amperes')),
                ('consumo_volts', models.FloatField(verbose_name='Consumo em volts')),
                ('canais', models.IntegerField(verbose_name='Quantidade de canais')),
                ('armazenamento', models.IntegerField(verbose_name='Quantidade de armazenamento em terabyte')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cftv.Fabricante', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Cabo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('bitolas', models.FloatField(verbose_name='Bitola')),
                ('aplicacao', models.CharField(max_length=50, verbose_name='Aplicação')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cftv.Fabricante', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Cabo',
                'verbose_name_plural': 'Cabos',
            },
        ),
    ]
