# Generated by Django 3.0.7 on 2020-06-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cftv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='armazenamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de armazenamento em terabyte'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='canais',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de canais'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='consumo_amper',
            field=models.FloatField(blank=True, null=True, verbose_name='Consumo em amperes'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='consumo_volts',
            field=models.FloatField(blank=True, null=True, verbose_name='Consumo em volts'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='infra',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distania do Infra vermelho'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='lente',
            field=models.FloatField(blank=True, null=True, verbose_name='Tamanho da lente'),
        ),
    ]
