# Generated by Django 3.0.7 on 2020-06-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cftv', '0002_auto_20200622_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentocftv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento_cftv', models.CharField(max_length=100, verbose_name='Equipamento')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('infra', models.IntegerField(blank=True, null=True, verbose_name='Distania do Infra vermelho')),
                ('lente', models.FloatField(blank=True, null=True, verbose_name='Tamanho da lente')),
                ('consumo_amper', models.FloatField(blank=True, null=True, verbose_name='Consumo em amperes')),
                ('consumo_volts', models.FloatField(blank=True, null=True, verbose_name='Consumo em volts')),
                ('canais', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de canais')),
                ('armazenamento', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de armazenamento em terabyte')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabricante_fabricante', to='cftv.Fabricante', verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
