# Generated by Django 3.0.7 on 2020-07-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('cftv', '0004_auto_20200627_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='cftvorcamento',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente', verbose_name='CLiente'),
            preserve_default=False,
        ),
    ]
