# Generated by Django 3.0.7 on 2020-07-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cftv', '0005_cftvorcamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cftvorcamento',
            name='ambiente',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Semi-aberto', 'Semi-aberto'), ('Externo', 'Externo'), ('Abertura', 'Abertura')], max_length=15, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='cftvorcamento',
            name='imagem',
            field=models.ImageField(upload_to='media/local', verbose_name='Imagem do local'),
        ),
    ]
