# Generated by Django 3.0.7 on 2020-07-30 02:04

import cftv.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('cftv', '0007_auto_20200729_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cftvorcamento',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=cftv.models.get_file_path, verbose_name='Imagem do local'),
        ),
    ]
